// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjkjuyzeuykpmomedpia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqa2p1eXpldXlrcG1vbWVkcGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyODA1MzIsImV4cCI6MjA3MDg1NjUzMn0.ooSdPhIMM8pn8Ry3Rrur_yQdCoRmks2eKIsink7O584";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});